services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eurogips_landing
    restart: always
    ports:
      - "3100:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
